### ISSUE TITLE
Migrate existing database

### ISSUE THREAD

**Issue by Watchwolf** [georgemarshall/django-cryptography#11]
Hello,

Have you an idea how I can migrate an existing database in order to user django-cryptography ?

I am planning to use it in a existing database. Currently the migration only convert charfield to blob but do not encrypt the data.

I am searching to do it manually but right now I do not have a solution.

**Comment by georgemarshall** [comment]
I have an example of this in the test cases, check it out at https://github.com/georgemarshall/django-cryptography/tree/master/tests/fields/test_migrations_normal_to_encrypted, hopefully that helps.

**Comment by TheBlusky** [comment]
Facing the same issue here. Did you manage to do it ?

**Comment by Julioocz** [comment]
Follow django fernet procedure. It worked for me https://django-fernet-fields.readthedocs.io/en/latest/#migrations

**Comment by thismatters** [comment]
Here is the migration template I cooked up for doing exactly this: https://gist.github.com/thismatters/53787f2d021fa5a1df640cd7b98d1185

**Comment by georgemarshall** [comment]
Documentation has been added to cover this.

https://django-cryptography.readthedocs.io/en/latest/migrating.html
