### ISSUE TITLE
Django 2.0.2 and Python 3.6.0

### ISSUE THREAD

**Issue by sanderbrauwers** [georgemarshall/django-cryptography#13]
I did exactly as in the example,

I even tried with a default value
```test_encrypt = encrypt(models.CharField(max_length=300,default="test_me"))```

However when I look in the database its just stored as text

**Comment by ADR-007** [comment]
Also, I can't find any test that checks that the text is really encrypted.

**Comment by tmanOC** [comment]
I used it with sqlite and it shows up as BLOB. And definitely looks nothing like what I typed in when I view the binary data.

**Comment by georgemarshall** [comment]
Existing fields cannot be encrypted in place, here is a reference to a previous discussion about migrating data.
https://github.com/georgemarshall/django-cryptography/issues/11#issuecomment-367238433
