### ISSUE TITLE
How to get the encrypted fields in django admin?

### ISSUE THREAD

**Issue by invinciblycool** [georgemarshall/django-cryptography#15]
I have successfully encrypted data and I have confirmed it after checking the tables.
But when I view the data in django admin interface, it comes out as plain text most probably because of the bi-directional nature of the `encrypt` wrapper.
Is there any way to override this nature and display encrypted data in the django admin.

**Comment by thismatters** [comment]
Wouldn't a better solution be to simply not display the sensitive information in the django admin?

What would be the point of displaying the data (still encrypted) in admin?

**Comment by invinciblycool** [comment]
Well, I had a special case here.
But yeah, it would be better not to display it.
Closing this.
