### ISSUE TITLE
Django 3.0 Compatibility 

### ISSUE THREAD

**Issue by mrname** [georgemarshall/django-cryptography#17]
Not that it is a rush or anything, but while running tests that require data migrations, the following warning is thrown:

`usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py:995: RemovedInDjango30Warning: Remove the context parameter from EncryptedCharField.from_db_value(). Support for it will be removed in Django 3.0.
  RemovedInDjango30Warning`

**Comment by thismatters** [comment]
I'm seeing a bunch of these as well. If you want to stop seeing them and you're using pytest then add this to your `pytest.ini`: 
```
filterwarnings =
    ignore::PendingDeprecationWarning
```

**Comment by thismatters** [comment]
If you're using Django 2.2 you'll have to change that to 

```
filterwarnings =

**Comment by nidshar** [comment]
Is there any way to fix these warnings instead of ignoring?

**Comment by thismatters** [comment]
The fix is to roll back to a fully supported Django version (2.0 as indicated by the readme). Moreover, there isn't _really_ a problem unless you migrate to Django 3.0 when it is released.

**Comment by georgemarshall** [comment]
Fixes for this have been merged
