### ISSUE TITLE
Could not encripte custom auth user email field

### ISSUE THREAD

**Issue by lijoev** [georgemarshall/django-cryptography#28]
I have modified django auth to use email as my username. I need to save the email encripted using django-cryptography. I tried to use encrypt function in email field in my model.py. but it throws me the below error

`django.core.exceptions.FieldError: Unsupported lookup 'exact' for EncryptedEmailField or join on the field not permitted, perhaps you meant exact or iexact?
`

I get this error when i create superuser and register new user.

**Comment by georgemarshall** [comment]
Encrypted fields are not indexable, as such you are not able to perform any matches against the fields contents.

**Comment by Bastien-Brd** [comment]
@lijoev my comment on another similar issue might help you: https://github.com/georgemarshall/django-cryptography/issues/10#issuecomment-553347255
