### ISSUE TITLE
Does not support Django 3.0

### ISSUE THREAD

**Issue by danny-zorroa** [georgemarshall/django-cryptography#31]
In 3.0 django.utils.six has been dropped and they recommend switching to the standard six lib. When trying run the `manage.py collectstatic` command the following exception is thrown.

File "/root/.local/lib/python3.6/site-packages/django_cryptography/fields.py", line 6, in <module>
    from django.utils import six
ImportError: cannot import name 'six'

**Comment by georgemarshall** [comment]
This has already been addressed in #30 and I will try to cut a release of it shortly.
