### ISSUE TITLE
Django 3.0 Import Error

### ISSUE THREAD

**Issue by xaiyeon** [georgemarshall/django-cryptography#32]
**Summary:**
Django 3.0 cannot import name six. Can you update the package to use the new six package?

Similar: [Django 3.0 Six - SO](https://stackoverflow.com/questions/59193514/importerror-cannot-import-name-six-from-django-utils)

**Traceback:**
`  File "\app\src\core\main\api\vevnp\lib\site-packages\django_cryptography\fields.py", line 6, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (\src\core\main\api\vevnp\lib\site-packages\django\utils\__init__.py)
(vevnp)`

**Comment by georgemarshall** [comment]
Fixed in #30
