### ISSUE TITLE
SQL query to decrypt field

### ISSUE THREAD

**Issue by daniel12564** [georgemarshall/django-cryptography#48]
Hi,
I'm generating some reports with data obtained via SQL queries but now some of this fields are encrypted because of client request. I would like to know if it's possible to build a query to obtain the decrypted value of an encrypted field.
Thanks

**Comment by georgemarshall** [comment]
While it is possible to extend SQL databases with custom function calls capable of decoding the encrypted bytes. You would be fighting an uphill battle of re-implementing the key derivation function (KDF) and decryption functions as something that can be accessed via a SQL query.

As such this request goes beyond the scope of this project. The intention of this Django Module is to restrict access of the data to the application layer only, hence why it is stored as encrypted bytes in the database.
