### ISSUE TITLE
Django-3.1 not supported? 

### ISSUE THREAD

**Issue by raratiru** [georgemarshall/django-cryptography#50]
The tests do not cover Django-3.1, is it not supported? 
Although it is somehow early, I have the same question for Python-3.9.

**Comment by emilpriver** [comment]
Wondering the same. 
Get this error when using 3.1

`Unsupported lookup 'exact' for EncryptedCharField or join on the field not permitted, perhaps you meant exact or iexact?`

**Comment by raratiru** [comment]
This project seems not to be actively maintained. 

On the other hand, [django-mirage-field](https://github.com/luojilab/django-mirage-field), currently keeps up with the pace.

**Comment by r1bnc** [comment]
Seems to work with Django 3.1.7, i have made a sample project with it on gitlab.
