### ISSUE TITLE
Django 4.0

### ISSUE THREAD

**Issue by lmbak** [georgemarshall/django-cryptography#62]
Django 4.0 removes the `ugettext_lazy` function from the `django.utils.translation` module (see the changes [here](https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0)).

This function is [used in the `fields.py` module on line 7](https://github.com/georgemarshall/django-cryptography/blob/master/django_cryptography/fields.py#L7).

For django-cryptography to be compatible with django 4.0 this has to be rewritten.

**Comment by SpongeManiac** [comment]
I need this updated ASAP, this error is stopping me from developing.

**Comment by jensenbox** [comment]
I would love to get this change in play - I could set up a Github Action to replace parts of Travis as well if that is desired.

**Comment by milos1302** [comment]
Is this going to be solved any time soon?

**Comment by SpongeManiac** [comment]
Someone beat me to it, here is a forked fix: https://github.com/JaisPiyush/django-cryptography

**Comment by georgemarshall** [comment]
Fixed in #68
